[features]
seeds = false
skip-lint = false

[programs.devnet]
nft = "62eUAMqPKSQvG4M7CfyfNqygpcfMVAob4XRRf9DbYk6J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/emrekeskin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
